server:
  port: 9002
  servlet:
    context-path: /api/video-ai/business
spring:
  profiles:
    active: dev,dev.core,dev.api
#mybatis:
#  typeAliasesPackage: com.dsunsoft.*.*.entity
#  mapper-locations: classpath:mapper/**/*.xml