server:
  port: 8081
  servlet:
    context-path: /api
  #gzip压缩
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,application/javascript,text/html,text/xml,text/plain,text/javascript
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    include: dev.core,dev.api